version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: medicinas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: medicinas_db
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin" ]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 10s

  app:
    build: .
    container_name: medicinas-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/medicinas_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  mysql_data: