# Este archivo se usa cuando SPRING_PROFILES_ACTIVE=render

spring.jpa.show-sql=false

spring.jpa.hibernate.ddl-auto=validate

# SSL para PostgreSQL en Render
spring.jpa.properties.hibernate.connection.ssl=true
spring.jpa.properties.hibernate.connection.sslmode=require

# Optimización para Render
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Logging en producción
logging.level.root=WARN
logging.level.com.medicina=INFO
logging.level.org.hibernate.SQL=OFF

# Deshabilitar Spring Security para pruebas
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration