spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
logging.level.root=WARN
logging.level.com.medicina=INFO
logging.level.org.hibernate.SQL=OFF